import ProjectInterface from '~/models/interfaces/ProjectInterface';
import ProjectSphere from '~/constants/enum/ProjectSphere';
import ProjectGridItemType from '~/constants/enum/ProjectGridItemType';

const DesignProject: Array<ProjectInterface> = [
  {
    path: 'alba-dance',
    name: 'Al\'ba dance',
    sphere: ProjectSphere.IDENTITY,
    year: 2022,
    description: 'Identity for the AL\'BA magic brand, combining two dance styles: choreography and deeper dance sessions. The purpose was to create a unified corporate identity for the AL\'BA brand, opening a new door for women and helping them discover themselves and connect to true self-nature.',
    grid: [
      {
        name: 'image-01',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 12,
      },
      {
        name: 'image-02',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-03',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-04',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-05',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-06',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-07',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-08',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-09',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-10',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-11',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-12',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-13',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-14',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-15',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-16',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-17',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-18',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-19',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-20',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-21',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-22',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-23',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-24',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-25',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-26',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
      {
        name: 'image-27',
        type: ProjectGridItemType.IMAGE,
        description: 'Al\'ba dance',
        size: 6,
      },
    ],
  },
  {
    path: 'coat-of-arms',
    name: 'Coat of arms',
    sphere: ProjectSphere.LOGOTYPE,
    year: 2022,
    description: 'Behind a person is history. The coat of arms may contain visual information about what is behind this story. I have created a coat of arms to decorate things that are dear to my heart. You can order to design your personal or family’s coat of arms.',
    grid: [
      {
        name: 'image-01',
        type: ProjectGridItemType.IMAGE,
        description: 'Coat of arms',
        size: 4,
      },
      {
        name: 'image-02',
        type: ProjectGridItemType.IMAGE,
        description: 'Coat of arms',
        size: 4,
      },
      {
        name: 'image-03',
        type: ProjectGridItemType.IMAGE,
        description: 'Coat of arms',
        size: 4,
      },
      {
        name: 'image-04',
        type: ProjectGridItemType.IMAGE,
        description: 'Coat of arms',
        size: 12,
      },
    ],
  },
  {
    path: 'she',
    name: 'She Underwear',
    sphere: ProjectSphere.IDENTITY,
    year: 2022,
    description: 'Identity for a young bright underwear brand that began its history under the auspices of a bright lifestyle, courage, openness in style. At the same time, the brand is sensual and gentle. I tried to keep this contrast in identity. Enjoy your viewing!',
    grid: [
      {
        name: 'image-01',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 12,
      },
      {
        name: 'image-02',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
      {
        name: 'image-03',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
      {
        name: 'image-04',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
      {
        name: 'image-05',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
      {
        name: 'image-06',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
      {
        name: 'image-07',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
      {
        name: 'image-08',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
      {
        name: 'image-09',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
      {
        name: 'image-10',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
      {
        name: 'image-11',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
      {
        name: 'image-12',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
      {
        name: 'image-13',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
      {
        name: 'image-14',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
      {
        name: 'image-15',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
      {
        name: 'image-16',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
      {
        name: 'image-17',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
      {
        name: 'image-18',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
      {
        name: 'image-19',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
      {
        name: 'image-20',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
      {
        name: 'image-21',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
      {
        name: 'image-22',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
      {
        name: 'image-23',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
      {
        name: 'image-24',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
      {
        name: 'image-25',
        type: ProjectGridItemType.IMAGE,
        description: 'She Underwear',
        size: 6,
      },
    ],
  },
  {
    path: 'urban_trend',
    name: 'Urban Trend',
    sphere: ProjectSphere.IDENTITY,
    year: 2022,
    description: 'Identity and branding for a brand that creates high-quality hair products.',
    grid: [
      {
        name: 'image-01',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
      },
      {
        name: 'image-02',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-03',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-04',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-05',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-06',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-07',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-08',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-09',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-10',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-11',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-12',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-13',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-14',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-15',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
      },
      {
        name: 'image-16',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-17',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-18',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
      },
      {
        name: 'image-19',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-20',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-21',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-22',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-23',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-24',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-25',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-26',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-27',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-28',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-29',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-30',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
      },
      {
        name: 'image-31',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-32',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
      },
      {
        name: 'image-33',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
        hasMask: true,
      },
      {
        name: 'image-34',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
      },
      {
        name: 'image-35',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
      },
      {
        name: 'image-36',
        type: ProjectGridItemType.IMAGE,
        description: 'Urban Trend',
        size: 6,
      },
    ],
  },
  {
    path: 'fragile-dreams',
    name: 'Fragile dreams',
    sphere: ProjectSphere.COLLAGE,
    year: 2021,
    description: 'Series of collages on the theme of dreams.',
    grid: [
      {
        name: 'image-01',
        type: ProjectGridItemType.IMAGE,
        description: 'Fragile dreams',
        size: 4,
      },
      {
        name: 'image-02',
        type: ProjectGridItemType.IMAGE,
        description: 'Fragile dreams',
        size: 4,
      },
      {
        name: 'image-03',
        type: ProjectGridItemType.IMAGE,
        description: 'Fragile dreams',
        size: 4,
      },
    ],
  },
  {
    path: 'hipo-card',
    name: 'Hipo card',
    sphere: ProjectSphere.PRINT,
    year: 2021,
    description: 'Hipo – media / store / community. I have been working on creating printed materials for the brand. Developed a design for a postcard that has become a tool for analyzing life on the balance wheel.',
    grid: [
      {
        name: 'image-01',
        type: ProjectGridItemType.IMAGE,
        description: 'Hipo card',
        size: 12,
      },
      {
        name: 'image-02',
        type: ProjectGridItemType.IMAGE,
        description: 'Hipo card',
        size: 6,
      },
      {
        name: 'image-03',
        type: ProjectGridItemType.IMAGE,
        description: 'Hipo card',
        size: 6,
      },
    ],
  },
  {
    path: 'merkaba',
    name: 'Merkaba',
    sphere: ProjectSphere.IDENTITY,
    year: 2020,
    description: 'Merkaba is an electronic music festival for which I created a identity. I tried to convey the mood of the festival in the identity as much as possible and solve the tasks that were set by the organizers.',
    grid: [
      {
        name: 'image-00',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 12,
      },
      {
        name: 'image-01',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-02',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-03',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-04',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-05',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-06',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-07',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-08',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-09',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-10',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-11',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-12',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-13',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-14',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-15',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-16',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-17',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-18',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-19',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-20',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-21',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-22',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-23',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-24',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-25',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'image-26',
        type: ProjectGridItemType.IMAGE,
        description: 'Merkaba',
        size: 6,
      },
      {
        name: 'video-01',
        type: ProjectGridItemType.VIDEO,
        description: 'Merkaba',
        size: 12,
      },
    ],
  },
  {
    path: 'hermitage-wine',
    name: 'Hermitage wine',
    sphere: ProjectSphere.PACKAGING,
    year: 2020,
    description: 'Wine label design.',
    grid: [
      {
        name: 'image-01',
        type: ProjectGridItemType.IMAGE,
        description: 'Hermitage wine',
        size: 12,
      },
      {
        name: 'image-02',
        type: ProjectGridItemType.IMAGE,
        description: 'Hermitage wine',
        size: 6,
      },
      {
        name: 'image-03',
        type: ProjectGridItemType.IMAGE,
        description: 'Hermitage wine',
        size: 6,
      },
    ],
  },
];

export default DesignProject;
